### ISSUE TITLE
1.19.3 - Mod version 1.9.1 - Can't seem to edit nbt easily

### ISSUE THREAD

**Issue by TahoeBennie** [mega12345mega/NBT-Editor#26] opened 2023-01-17 02:53 UTC
Whenever I try to edit an item's nbt, I select what I want to modify, but then as soon as I click on the text box to modify it, it thinks I clicked away and therefore it won't let me edit what I wanted to edit, because the text goes away before I can click into it, and then it wants me to modify a blank value unassigned to anything to edit. It is also broken with expanding it and I'm not quite sure why that doesn't work either, it just doesn't save what I changed when I exit the enlarged part, so generally editing as a whole doesn't seem to work. Only way I can edit nbt is by expanding the menu when I haven't selected anything, and just changing the raw nbt as a whole works.

**Comment by mega12345mega** [comment] 2023-01-18 00:54
I've just checked, and this is confirmed to affect 1.19.3 specifically. After looking through the decompiled code, I've found the issue pretty easily.
I hadn't bothered to check this, as I didn't realize the behavior of Minecraft's internal class had changed. :/

There appears to be a workaround:
After clicking the key to modify, press Shift + Tab until the value field is selected. You can also press Shift + Tab until the expand button is selected, then press space to open it.

After experimenting a bit more, there seems to be some related bugs, where most of the fields can't be modified unless you tab to them.
This seems to affect the editor screen specifically, but I wouldn't be surprised if there are bugs in other places due to this change.

**Comment by Radplayz** [comment] 2023-01-22 00:36
The workaround does not work with changing the count of items, and when i attempted, the game straight up crashed

**Comment by mega12345mega** [comment] 2023-01-22 08:08
If I remember correctly, the workaround for changing the number of items requires you to go in the forward order (using just Tab). Can you send the crash report?

**Comment by Radplayz** [comment] 2023-01-22 19:55
Seems the crash was caused by a different mod i have installed, however i did check, and it is not possible to go to the item count using just tab

**Comment by HyperSoop** [comment] 2023-01-30 14:54
Is there also an issue with extended chat limit not actually being extended? It's the "pretty much everything is broken" issue

**Comment by HyperSoop** [comment] 2023-02-05 11:02
Is not being able to put shulker boxes into shulker boxes with /open also known?

**Comment by mega12345mega** [comment] 2023-02-07 00:31
> Is not being able to put shulker boxes into shulker boxes with /open also known?

I've just completed the final checks in releasing the update before seeing this. I checked quickly, and I'm not able to replicate this issue. It's possible I've made a change that has inadvertently fixed this, but due to how `/open` works, this shouldn't be possible in the first place. Can you create a new issue with more details? I'm going to continue with releasing the update, and will close this issue when complete.

**Comment by mega12345mega** [comment] 2023-02-07 01:54
I've fixed this in the latest version (v1.10.0)! I believe I have gotten everything working, but this is a complicated enough bug that there might have been something that I have missed. Since this is now closed, related bugs should be opened under a new issue so I don't miss them.

**Closed by mega12345mega** 2023-02-07 01:54 UTC
Labels: bug, completed - not yet rolled out
