### ISSUE TITLE
Editing sign NBT don't work in the latest update

### ISSUE THREAD

**Issue by Maks7594** [mega12345mega/NBT-Editor#63] opened 2023-07-14 22:52 UTC
Editing the sign NBT data to have some text doesn't work. The sign is blank.

**Comment by HyperSoop** [comment] 2023-07-15 05:17
try doing this in singleplayer; you can't do some NBT editing on servers without having OP

**Comment by mega12345mega** [comment] 2023-07-18 23:51
As far as I'm aware, everything should work the same regardless of op or single vs multi. @HyperSoop can you specify what only works with OP (possibly in a different issue)? It is possible Minecraft started "regulating" creative mode's ability to create any item - if so that's very unfortunate. All edits are sent through the same creative slot update packet, so I would expect all edits to function the same.

@Maks7594 which Minecraft version are you using? 1.19.4 and below handle signs differently then 1.20 and above, since 1.20 supports editing both sides. If you happen to be trying to place a sign from 1.19.4 in a 1.20 world, you will need to run `/itemfactory signboard import` first. If that isn't the issue, I'm assuming that the editor itself shows the text (even when reopened), it just doesn't show when placed down.

**Comment by HyperSoop** [comment] 2023-07-19 07:19
> It is possible Minecraft started "regulating" creative mode's ability to create any item

I am not sure. It might be a patch in PaperMC. What's prevented is mainly things that can give you OP, like spawn eggs of command minecarts and falling command blocks/ spawners, i think also signs and books, but again I'm not sure.

**Comment by mega12345mega** [comment] 2024-01-26 19:03
Since I haven't gotten any more information on this issue, and it seems to work fine in my own testing, I'm closing. If the issue is still occurring, please create another issue (unless you're able to re-open this one).

**Closed by mega12345mega** 2024-01-26 19:03 UTC
Labels: bug
